import os
import argparse

import numpy as np

import h5py

from exetera.core.session import Session

def generate_command(vsize, vcount, rootdir):

    r = np.random.RandomState(12345678)
    for i in range(vcount):
        np.save(os.path.join(rootdir, "right_data_{}".format(i)), r.randint(100, size=vsize, dtype=np.int32))

    np.save(os.path.join(rootdir, "ids"), np.arange(vsize, dtype=np.int64))

    mapping = [0, 1, 1, 2]
    len_mapping = len(mapping)
    left_ids = np.zeros(vsize, dtype=np.int64)

    for i in range(vsize):
        base = i // len_mapping
        in_map = i % len_mapping
        left_ids[i] = mapping[in_map] + base * len_mapping

    np.save(os.path.join(rootdir, "fk_ids"), left_ids)


def import_command(input, vcount, output):
    s = Session()
    with h5py.File('/home/ben/covid/benchmarking.hdf5', 'w') as hf:
        for name in ('fk_ids', 'ids'):
            print('importing "{}"'.format(name))
            n = np.load('/home/ben/covid/{}.npy'.format(name))
            df = s.create_numeric(hf, name, 'int64')
            df.data.write(n)

        for v in range(vcount):
            print('importing "right_data_{}"'.format(v))
            n = np.load('/home/ben/covid/right_data_{}.npy'.format(v))
            df = s.create_numeric(hf, 'right_data_{}'.format(v), 'int32')
            df.data.write(n)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    subparsers = parser.add_subparsers(dest='command')
    subparsers.required = True

    generate_subcmd = subparsers.add_parser('generate')
    generate_subcmd.add_argument('-s', '--size', required=True,
                                 help="the size of each field in number of elements")
    generate_subcmd.add_argument('-c', '--count', required=True,
                                 help="the number of fields to be generated (excluding the keys)")
    generate_subcmd.add_argument('-o', '--output', required=True,
                                 help="the directory to which the data should be written. This is"
                                    "created if it does not yet exist")

    import_subcmd = subparsers.add_parser('import')
    import_subcmd.add_argument('-i', '--input', required=True,
                               help="the input folder containing the data generated by the generate command")
    import_subcmd.add_argument('-c', '--count', required=True,
                               help="the number of fields to be imported (must be equal to or lower than the number"
                                     "of fields generated by the generate command)")
    import_subcmd.add_argument('-o', '--output', required=True,
                               help="the name of the exetera dataset to write to (will overwrite an existing file)")

    args = parser.parse_args()

    if args.command == 'generate':
        generate_command(args.size, args.count, args.output)
    elif args.command == 'import':
        import_command(args.input, args.output)
    # else:
    #     print("command 'args.command' is not recognised")
